### ISSUE TITLE
How to train stanza NER with my training dataset

### ISSUE THREAD

**Issue by isaac47** [yuhui-zh15/stanza-train#1] opened 2020-05-01 09:59 UTC
Hello,

And thanks for your job. Stanza is realy nice. I am trying to train a custom NER model, which integrate stanza tags and my custom tags. I have build the training data. 

How can I use this training data to train NER model?
Do I use this: bash scripts/run_ner.sh English-TEST --max_steps 1000 --word_emb_dim 5? and how to specify my custom training data path?

**Comment by yuhui-zh15** [comment] 2020-05-01 16:25
Hi @isaac47, this repo provides a runnable tutorial to train NER models. The simplest way is to directly replace your data in this repo. Otherwise, you need to change the configurations from https://github.com/yuhui-zh15/stanza-train/blob/master/config/config.sh.

**Comment by isaac47** [comment] 2020-05-02 11:45
Hi @yuhui-zh15  and thanks for your response. I have reproduce the repo and I have a problem at the word2vec step.
After running `bash scripts/download_vectors.sh ${wordvec_dir}` , the script generate an error because of the word separator in the train.bio file. I fix the .bio file. 

So my question is how to run again the word2vec step without donwload the word-embeddings-conll17.tar files once more?

**Comment by yuhui-zh15** [comment] 2020-05-03 18:06
@isaac47 Sorry but I do not understand what the problem is? Running `bash scripts/download_vectors.sh ${wordvec_dir}` will only download word vectors, it seems this is not related to `word separator in the train.bio file`?

**Comment by isaac47** [comment] 2020-05-04 07:58
@yuhui-zh15 running the` bash scripts/download_vectors.sh ${wordvec_dir}` will download word vectors from conll17 and try automatically to apply it on my `train.bio file`.

So I want to know how to only run the construction of the `en.vectors.xz file` when I created a new train.bio file.

**Comment by yuhui-zh15** [comment] 2020-05-04 17:25
@isaac47 Running the bash scripts/download_vectors.sh ${wordvec_dir} will **ONLY** download word vectors. You can directly replace the toy vectors with the downloaded vectors in `xz` format. You **do not** need to modify the downloaded vectors regardless of your training data.

**Comment by isaac47** [comment] 2020-05-15 11:20
Hello,

I face a problem at the training step because of the `en.vectors.xz` file. in your example, you build a custom `en.vectors.xz` in regards of yout train.bio. How can I achieve that after downloded the CoNLL files?

**Comment by yuhui-zh15** [comment] 2020-05-25 07:46
Hi @isaac47, sorry that I didn't notice your question. 

You do not need to modify the downloaded vectors and perform any preprocessing regardless of your training data. In this repo the `en.vectors.xz` is just a toy example that I made to be small in order that you can run this code quickly. In the real experiment you should replace this example with downloaded vector files and no need to modify it at all.

**Comment by yuhui-zh15** [comment] 2020-05-31 20:45
Closed this issue now. Feel free to reopen if you have other questions :)

**Closed by yuhui-zh15** 2020-05-31 20:45 UTC
